baseURL = "https://miaomothers.github.io/"
languageCode = "zh-cn"
title = "我的博客"
theme = "PaperMod"
publishDir = "docs"

# 启用 Emoji 支持
enableEmoji = true

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 40

[params]
  # 主题模式 auto, light, dark
  defaultTheme = "auto"
  # 显示分享按钮
  ShowShareButtons = true
  # 显示文章阅读时间
  ShowReadingTime = true
  # 显示目录
  ShowToc = true
  # 显示面包屑导航
  ShowBreadCrumbs = true
  # 显示代码复制按钮
  ShowCodeCopyButtons = true
  # 显示字数统计
  ShowWordCount = true
  # 显示RSS链接
  ShowRssButtonInSectionTermList = true
